---

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8010/eureka/

server:
  port: 8020
  
#words= NotApplicable

# For simplicity, disable security when posting to bus/refresh:  
management:
  security:
    enabled: false